{{- if .Values.routerSpec.enableRouter -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment-router"
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "chart.routerLabels" . | nindent 4 }}
spec:
{{- if .Values.routerSpec.autoscaling.enabled }}
  replicas: {{ .Values.routerSpec.autoscaling.minReplicas }}
{{- else }}
  replicas: {{ .Values.routerSpec.replicaCount }}
{{- end }}
  {{- include "chart.routerStrategy" . | nindent 2 }}
  selector:
    matchLabels:
    {{- include "chart.routerLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "chart.routerLabels" . | nindent 8 }}
      {{- with .Values.routerSpec.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}-router-service-account
      {{- if .Values.routerSpec.priorityClassName }}
      priorityClassName: {{ .Values.routerSpec.priorityClassName | quote }}
      {{- end }}
      {{- if not (empty .Values.routerSpec.affinity) }}
      affinity:
        {{- toYaml .Values.routerSpec.affinity | nindent 8 }}
      {{- else if .Values.routerSpec.nodeSelectorTerms }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            {{- with .Values.routerSpec.nodeSelectorTerms }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- end }}
      {{- with .Values.routerSpec.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.routerSpec.securityContext }}
      securityContext:
        {{- toYaml .Values.routerSpec.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: router-container
        image: "{{ .Values.routerSpec.repository | default "lmcache/lmstack-router" }}:{{ .Values.routerSpec.tag | default "latest" }}"
        imagePullPolicy: "{{ .Values.routerSpec.imagePullPolicy | default "Always" }}"
        {{- if .Values.routerSpec.containerSecurityContext }}
        securityContext:
          {{- toYaml .Values.routerSpec.containerSecurityContext | nindent 10 }}
        {{- end }}
        env:
          {{- if .Values.routerSpec.hf_token }}
          - name: HF_TOKEN
            value: "{{ .Values.routerSpec.hf_token }}"
          {{- end }}
          - name: PYTHONHASHSEED
            value: "123"
          - name: LMCACHE_LOG_LEVEL
            value: "DEBUG"
          {{- if .Values.servingEngineSpec.enableEngine -}}
          {{- $vllmApiKey := $.Values.servingEngineSpec.vllmApiKey }}
          {{- if $vllmApiKey }}
          - name: VLLM_API_KEY
            {{- if kindIs "string" $vllmApiKey }}
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: vllmApiKey
            {{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ $vllmApiKey.secretName }}
                key: {{ $vllmApiKey.secretKey }}
            {{- end }}
          {{- end }}
          {{- else }}
          {{- $vllmApiKey := $.Values.routerSpec.vllmApiKey }}
          {{- if $vllmApiKey }}
          - name: VLLM_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ $vllmApiKey.secretName }}
                key: {{ $vllmApiKey.secretKey }}
          {{- end }}
          {{- end }}
        args:
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "{{ .Values.routerSpec.containerPort }}"
          - "--service-discovery"
          - "{{ default "k8s" .Values.routerSpec.serviceDiscovery }}"
          {{- if eq .Values.routerSpec.serviceDiscovery "k8s" }}
          - "--k8s-namespace"
          - "{{ .Release.Namespace }}"
          - "--k8s-service-discovery-type"
          - "{{ default "pod-ip" .Values.routerSpec.k8sServiceDiscoveryType }}"
          {{- if .Values.servingEngineSpec.enableEngine }}
          - "--k8s-label-selector"
          - {{ include "labels.toCommaSeparatedList" .Values.servingEngineSpec.labels }}
          {{- end }}
          {{- end }}
          {{- if eq .Values.routerSpec.serviceDiscovery "static" }}
          - "--static-backends"
          - "{{ required "When using static service discovery, .Values.routerSpec.staticBackends is a required value" .Values.routerSpec.staticBackends }}"
          - "--static-models"
          - "{{ required "When using static service discovery, .Values.routerSpec.staticModels is a required value" .Values.routerSpec.staticModels }}"
          {{- end }}
          - "--routing-logic"
          - "{{ .Values.routerSpec.routingLogic }}"
          {{- if .Values.routerSpec.sessionKey }}
          - "--session-key"
          - "{{ .Values.routerSpec.sessionKey }}"
          {{- end }}
          {{- if .Values.routerSpec.engineScrapeInterval }}
          - "--engine-stats-interval"
          - "{{ .Values.routerSpec.engineScrapeInterval }}"
          {{- end }}
          {{- if .Values.routerSpec.requestStatsWindow }}
          - "--request-stats-window"
          - "{{ .Values.routerSpec.requestStatsWindow }}"
          {{- end }}
          {{- if .Values.routerSpec.extraArgs }}
          {{- toYaml .Values.routerSpec.extraArgs | nindent 10 }}
          {{- end }}
          {{- if .Values.routerSpec.lmcacheControllerPort }}
          - "--lmcache-controller-port"
          - "{{ .Values.routerSpec.lmcacheControllerPort }}"
          {{- end }}
          {{- if .Values.routerSpec.otel.endpoint }}
          - "--otel-endpoint"
          - "{{ .Values.routerSpec.otel.endpoint }}"
          - "--otel-service-name"
          - "{{ .Values.routerSpec.otel.serviceName | default "vllm-router" }}"
          {{- if .Values.routerSpec.otel.secure }}
          - "--otel-secure"
          {{- end }}
          {{- end }}
        {{- if .Values.routerSpec.resources }}
        resources:
          {{- if .Values.routerSpec.resources.requests }}
          requests:
            cpu: "{{ .Values.routerSpec.resources.requests.cpu }}"
            memory: "{{ .Values.routerSpec.resources.requests.memory }}"
          {{- end }}
          {{- if .Values.routerSpec.resources.limits }}
          limits:
            {{- if .Values.routerSpec.resources.limits.cpu }}
            cpu: "{{ .Values.routerSpec.resources.limits.cpu }}"
            {{- end }}
            {{- if .Values.routerSpec.resources.limits.memory }}
            memory: "{{ .Values.routerSpec.resources.limits.memory }}"
            {{- end }}
          {{- end }}
        {{- end }}
        ports:
          - name: "router-cport"
            containerPort: {{ .Values.routerSpec.containerPort }}
          - name: "lmcache-port"
            containerPort: 9000
        livenessProbe:
          initialDelaySeconds: {{ .Values.routerSpec.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.routerSpec.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.routerSpec.livenessProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.routerSpec.livenessProbe.httpGet.path }}
            port: {{ .Values.routerSpec.containerPort }}
        startupProbe:
          initialDelaySeconds: {{ .Values.routerSpec.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.routerSpec.startupProbe.periodSeconds }}
          failureThreshold: {{ .Values.routerSpec.startupProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.routerSpec.startupProbe.httpGet.path }}
            port: {{ .Values.routerSpec.containerPort }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.routerSpec.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.routerSpec.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.routerSpec.readinessProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.routerSpec.readinessProbe.httpGet.path }}
            port: {{ .Values.routerSpec.containerPort }}
{{- end }}
