{{- if .Values.servingEngineSpec.enableEngine -}}
{{- range $modelSpec := .Values.servingEngineSpec.modelSpec }}
{{- if and $modelSpec.pdb $modelSpec.pdb.enabled }}
{{- with $ }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Name }}-{{ $modelSpec.name }}-pdb-vllm"
  namespace: {{ .Release.Namespace }}
  {{- with $modelSpec.pdb.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $modelSpec.pdb.annotations }}
  annotations:
   {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $modelSpec.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ $modelSpec.pdb.minAvailable | default 0 }}
  {{- end }}
  selector:
    matchLabels:
      model: {{ $modelSpec.name }}
      helm-release-name: {{ .Release.Name }}
    {{- include "chart.engineStandardLabels" (dict "releaseName" .Release.Name "modelName" $modelSpec.name "chartName" .Chart.Name) | nindent 6 }}
    {{- include "chart.engineLabels" . | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
