
{{- if .Values.servingEngineSpec.enableEngine -}}
{{- range $modelSpec := .Values.servingEngineSpec.modelSpec }}
{{- with $ -}}
{{- if and (hasKey $modelSpec "pvcStorage") (not (empty $modelSpec.pvcStorage)) (kindIs "string" $modelSpec.pvcStorage) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{$modelSpec.name}}-storage-claim"
  namespace: {{ .Release.Namespace }}
  {{- if not (empty $modelSpec.pvcLabels) }}
  labels:
    {{- toYaml $modelSpec.pvcLabels | nindent 4}}
  {{- end }}
  {{- if not (empty $modelSpec.pvcAnnotations) }}
  annotations:
    {{- toYaml $modelSpec.pvcAnnotations | nindent 4}}
  {{- end }}
spec:
  accessModes:
    {{- if $modelSpec.pvcAccessMode }}
    {{- toYaml $modelSpec.pvcAccessMode | nindent 4 }}
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  resources:
    requests:
      storage: {{ $modelSpec.pvcStorage }}
  {{- if hasKey $modelSpec "storageClass" }}
  storageClassName: "{{ $modelSpec.storageClass }}"
  {{- end }}
  {{- if not (empty $modelSpec.pvcMatchLabels) }}
  selector:
    matchLabels:
      {{- toYaml $modelSpec.pvcMatchLabels | nindent 8 }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
