{{- if .Values.routerSpec.enableRouter -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-reader"
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""] # "" indicates the core API group
{{- if .Values.routerSpec.k8sServiceDiscoveryType | default "pod-ip" | eq "pod-ip" }}
  resources: ["pods"]
{{- else }}
  resources: ["pods", "services", "endpoints"]
{{- end }}
  verbs: ["get", "watch", "list", "patch"]
{{- end }}

{{- if .Values.loraController.enableLoraController }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-lora-controller"
  labels:
    app.kubernetes.io/component: lora-controller
    helm-release-name: {{ .Release.Name }}
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["production-stack.vllm.ai"]
  resources: ["loraadapters"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["production-stack.vllm.ai"]
  resources: ["loraadapters/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["pods", "events", "secrets"]
  verbs: ["get", "list", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-leader-election-role"
  labels:
    app.kubernetes.io/component: leader-election
    helm-release-name: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
{{- end }}
