apiVersion: v2
name: vllm-stack
description: The stack deployment of vLLM

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.9

maintainers:
  - name: apostac

dependencies:
  - name: kube-prometheus-stack
    version: 82.4.3
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
  - name: prometheus-adapter
    version: 5.3.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-adapter.enabled
